### ISSUE TITLE
Input页面样式错位

### ISSUE THREAD

**Issue by Feng-JY** [fbchen/angular2-weui#2]
#### 可重现的在线演示
https://feng-jy.github.io/angular2-weui/index.html#/input

系统环境
- window 32 位:
- chrome 56:

#### 问题截图:
![qq 20170314165715](https://cloud.githubusercontent.com/assets/13466494/23892866/5549a4da-08d7-11e7-88f2-65d48a9a5b21.jpg)

#### WE-UI官网截图:
![qq 20170314165731](https://cloud.githubusercontent.com/assets/13466494/23892869/56f80af6-08d7-11e7-886c-a2ecf78e03ca.jpg)

**Comment by fbchen** [comment]
所有的`form`输入控件是继承抽象类 `/src/app/weui/input/WeUIFormControl` ，而`WeUIFormControl`中引入的 ：
```ts
-    /**
 -     * 设置基本样式
 -     */
 -    @HostBinding('class') get controlClass() {
 -        return WeUIFormControl.getBasicControlCls();
 -    }
```
导致了`input`标签的`class`样式被覆写，咱不明白具体原因，先删除该方法设置的样式。

**Comment by fbchen** [comment]
我增加了一个例子工程：[https://github.com/fbchen/angular2-weui-demo](https://github.com/fbchen/angular2-weui-demo)

**Comment by fbchen** [comment]
增加了在线例子：[https://fbchen.github.io/angular2-weui/](https://fbchen.github.io/angular2-weui/)

**Comment by Feng-JY** [comment]
好了。我宣传宣传这个UI，让更多的人用angular2,angular2-weui
