### ISSUE TITLE
ERROR while build with angular-cli

### ISSUE THREAD

**Issue by enixjin** [fbchen/angular2-weui#3]
angular-cli 1.0.2
angular 4.0.0
angular2-weui 0.9.3

while run "ng build --prod"
ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.checkbox.d.ts.WeUICheckbox.html (7,41): Property 'innerValue' does not exist on type 'WeUICheckbox'.

ERROR in /sandbox/workspaces/temp/test/angular/src/$$_gendir/node_modules/angular-weui/input/weui.checkbox.ngfactory.ts (227,31): Property 'innerValue' does not exist on type 'WeUICheckbox'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.checkbox.d.ts.WeUICheckbox.html (6,55): Property 'checked' does not exist on type 'WeUICheckbox'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.picker.d.ts.WeUIPicker.html (3,14): Property 'shown' does not exist on type 'WeUIPicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.picker.d.ts.WeUIPicker.html (3,14): Property 'shown' does not exist on type 'WeUIPicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.picker.d.ts.WeUIPicker.html (5,14): Property 'shown' does not exist on type 'WeUIPicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.picker.d.ts.WeUIPicker.html (5,14): Property 'shown' does not exist on type 'WeUIPicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.date.picker.d.ts.WeUIDatePicker.html (3,14): Property 'shown' does not exist on type 'WeUIDatePicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.date.picker.d.ts.WeUIDatePicker.html (3,14): Property 'shown' does not exist on type 'WeUIDatePicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.date.picker.d.ts.WeUIDatePicker.html (5,14): Property 'shown' does not exist on type 'WeUIDatePicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/picker/weui.date.picker.d.ts.WeUIDatePicker.html (5,14): Property 'shown' does not exist on type 'WeUIDatePicker'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/uploader/weui.uploader.d.ts.WeUIUploader.html (10,21): Property 'image' does not exist on type 'WeUIUploader'.

ERROR in /sandbox/workspaces/temp/test/angular/src/$$_gendir/node_modules/angular-weui/uploader/weui.uploader.ngfactory.ts (312,30): Property 'getUploadedFileCount' does not exist on type 'WeUIUploader'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/uploader/weui.uploader.d.ts.WeUIUploader.html (6,50): Property 'getFileCount' does not exist on type 'WeUIUploader'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.radio.d.ts.WeUIRadio.html (10,43): Property 'innerValue' does not exist on type 'WeUIRadio'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.radio.d.ts.WeUIRadio.html (10,21): Property 'innerValue' does not exist on type 'WeUIRadio'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.switch.d.ts.WeUISwitch.html (9,91): Property 'innerValue' does not exist on type 'WeUISwitch'.

ERROR in /sandbox/workspaces/temp/test/angular/src/$$_gendir/node_modules/angular-weui/input/weui.switch.ngfactory.ts (215,31): Property 'innerValue' does not exist on type 'WeUISwitch'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/input/weui.switch.d.ts.WeUISwitch.html (9,55): Property 'checked' does not exist on type 'WeUISwitch'.

ERROR in ng:///sandbox/workspaces/temp/test/angular/node_modules/angular-weui/actionsheet/weui.actionsheet.d.ts.WeUIActionSheet.html (4,14): Property 'shown' does not exist on type 'WeUIActionSheet'.

**Comment by fbchen** [comment]
hello, please use my new project on angular4 with weui! 
This is where you can find the source codes:
https://github.com/fbchen/angular4-weui

**Comment by enixjin** [comment]
cool
